// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDQul8TtGyipAzFnKcpkJZgPaFUv2TZ5U',
    appId: '1:213324049505:web:7152d05a9d6e1c08c2ce20',
    messagingSenderId: '213324049505',
    projectId: 'sample-10f65',
    authDomain: 'sample-10f65.firebaseapp.com',
    storageBucket: 'sample-10f65.appspot.com',
    measurementId: 'G-C1P99HQGGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsF58xXuyEXkG9kNtQeMFNoLBCQN3oRp8',
    appId: '1:213324049505:android:cab31b61c704abe5c2ce20',
    messagingSenderId: '213324049505',
    projectId: 'sample-10f65',
    storageBucket: 'sample-10f65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmZiQnrnZZj7byevlqjJkSRDSQX_RRVTA',
    appId: '1:213324049505:ios:252fe04914ec73cfc2ce20',
    messagingSenderId: '213324049505',
    projectId: 'sample-10f65',
    storageBucket: 'sample-10f65.appspot.com',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmZiQnrnZZj7byevlqjJkSRDSQX_RRVTA',
    appId: '1:213324049505:ios:252fe04914ec73cfc2ce20',
    messagingSenderId: '213324049505',
    projectId: 'sample-10f65',
    storageBucket: 'sample-10f65.appspot.com',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDQul8TtGyipAzFnKcpkJZgPaFUv2TZ5U',
    appId: '1:213324049505:web:718168465f5c8e4ec2ce20',
    messagingSenderId: '213324049505',
    projectId: 'sample-10f65',
    authDomain: 'sample-10f65.firebaseapp.com',
    storageBucket: 'sample-10f65.appspot.com',
    measurementId: 'G-YW7K152QVF',
  );
}
